import { SessionInfo } from './types';

export const MOCK_SESSIONS: SessionInfo[] = [
  // === WhatsApp — Holt AI Group ===
  {
    id: 'agent:kev:whatsapp:group:120363406322095214@g.us',
    key: 'agent:kev:whatsapp:group:120363406322095214@g.us',
    agent: 'kev',
    emoji: '🦈',
    status: 'working',
    model: 'claude-opus-4-6',
    channel: 'whatsapp',
    cost: 3.51,
    tokenUsage: { input: 82400, output: 23200, cacheRead: 48000, cacheWrite: 11200 },
    startedAt: new Date(Date.now() - 1800000).toISOString(),
    subagents: ['agent:rex-claude:subagent:2b2e2a31', 'agent:scout:subagent:d7e1f9', 'agent:pixel:subagent:a1b2c3'],
    label: 'kev-reef-orchestrator',
    recipient: 'Holt AI Group',
    isGroup: true,
  },
  {
    id: 'agent:rex-claude:subagent:2b2e2a31',
    key: 'agent:rex-claude:subagent:2b2e2a31',
    agent: 'rex-claude',
    emoji: '🦖',
    status: 'working',
    model: 'claude-opus-4-6',
    channel: 'subagent',
    cost: 0.45,
    tokenUsage: { input: 24000, output: 7200, cacheRead: 12000, cacheWrite: 2400 },
    startedAt: new Date(Date.now() - 900000).toISOString(),
    parentSession: 'agent:kev:whatsapp:group:120363406322095214@g.us',
    subagents: [],
    label: 'rex-reef-ultra-polish',
  },
  {
    id: 'agent:scout:subagent:d7e1f9',
    key: 'agent:scout:subagent:d7e1f9',
    agent: 'scout',
    emoji: '🔍',
    status: 'idle',
    model: 'claude-sonnet-4',
    channel: 'subagent',
    cost: 0.12,
    tokenUsage: { input: 6200, output: 1800, cacheRead: 4000, cacheWrite: 600 },
    startedAt: new Date(Date.now() - 3600000).toISOString(),
    parentSession: 'agent:kev:whatsapp:group:120363406322095214@g.us',
    subagents: [],
    label: 'nanoclaw-research',
  },
  {
    id: 'agent:pixel:subagent:a1b2c3',
    key: 'agent:pixel:subagent:a1b2c3',
    agent: 'pixel',
    emoji: '🎨',
    status: 'stopped',
    model: 'claude-sonnet-4',
    channel: 'subagent',
    cost: 0.08,
    tokenUsage: { input: 3000, output: 900, cacheRead: 2000, cacheWrite: 400 },
    startedAt: new Date(Date.now() - 5400000).toISOString(),
    parentSession: 'agent:kev:whatsapp:group:120363406322095214@g.us',
    subagents: [],
    label: 'reef-mockups',
  },

  // === WhatsApp — Adam DM ===
  {
    id: 'agent:kev:whatsapp:dm:6421234567@s.whatsapp.net',
    key: 'agent:kev:whatsapp:dm:6421234567@s.whatsapp.net',
    agent: 'kev',
    emoji: '🦈',
    status: 'idle',
    model: 'claude-opus-4-6',
    channel: 'whatsapp',
    cost: 1.20,
    tokenUsage: { input: 35000, output: 9800, cacheRead: 20000, cacheWrite: 4000 },
    startedAt: new Date(Date.now() - 7200000).toISOString(),
    subagents: [],
    label: 'kev-adam-chat',
    recipient: 'Adam',
    isGroup: false,
  },

  // === WhatsApp — DroneTrust Group ===
  {
    id: 'agent:kev:whatsapp:group:999888777@g.us',
    key: 'agent:kev:whatsapp:group:999888777@g.us',
    agent: 'kev',
    emoji: '🦈',
    status: 'stopped',
    model: 'claude-opus-4-6',
    channel: 'whatsapp',
    cost: 0.50,
    tokenUsage: { input: 15000, output: 4200, cacheRead: 9000, cacheWrite: 2000 },
    startedAt: new Date(Date.now() - 14400000).toISOString(),
    subagents: [],
    label: 'dronetrust-planning',
    recipient: 'DroneTrust Group',
    isGroup: true,
  },

  // === Telegram ===
  {
    id: 'agent:sentinel:telegram:chat:9988776655',
    key: 'agent:sentinel:telegram:chat:9988776655',
    agent: 'sentinel',
    emoji: '🛡️',
    status: 'working',
    model: 'claude-sonnet-4',
    channel: 'telegram',
    cost: 0.87,
    tokenUsage: { input: 28000, output: 8500, cacheRead: 15000, cacheWrite: 3000 },
    startedAt: new Date(Date.now() - 3200000).toISOString(),
    subagents: [],
    label: 'security-audit',
    recipient: 'DevOps Alerts',
    isGroup: true,
  },
  {
    id: 'agent:kev:telegram:dm:112233',
    key: 'agent:kev:telegram:dm:112233',
    agent: 'kev',
    emoji: '🦈',
    status: 'stopped',
    model: 'claude-opus-4-6',
    channel: 'telegram',
    cost: 0.33,
    tokenUsage: { input: 10000, output: 3000, cacheRead: 6000, cacheWrite: 1000 },
    startedAt: new Date(Date.now() - 86400000).toISOString(),
    subagents: [],
    label: 'telegram-test',
    recipient: 'Test User',
    isGroup: false,
  },

  // === Internal (no channel / heartbeat / cron) ===
  {
    id: 'agent:kev:internal:heartbeat',
    key: 'agent:kev:internal:heartbeat',
    agent: 'kev',
    emoji: '💓',
    status: 'idle',
    model: 'claude-haiku-4',
    channel: 'internal',
    cost: 0.02,
    tokenUsage: { input: 800, output: 200, cacheRead: 500, cacheWrite: 100 },
    startedAt: new Date(Date.now() - 600000).toISOString(),
    subagents: [],
    label: 'heartbeat',
    recipient: 'Heartbeat',
  },
  {
    id: 'agent:atlas:internal:cron:daily-report',
    key: 'agent:atlas:internal:cron:daily-report',
    agent: 'atlas',
    emoji: '🗺️',
    status: 'stopped',
    model: 'claude-sonnet-4',
    channel: 'internal',
    cost: 0.15,
    tokenUsage: { input: 5000, output: 1500, cacheRead: 3000, cacheWrite: 500 },
    startedAt: new Date(Date.now() - 43200000).toISOString(),
    subagents: [],
    label: 'daily-cost-report',
    recipient: 'Cron Jobs',
  },
];

export const MOCK_TERMINAL_LINES = [
  { type: 'system' as const, text: 'agent:kev:session:a3f8c2 connected' },
  { type: 'system' as const, text: 'Model: claude-opus-4-20250514 | Started: 19:14:32' },
  { type: 'agent' as const, text: "kev ▸ I'll start implementing the Session Explorer tree view. Let me read the architecture doc first..." },
  { type: 'tool' as const, text: '⚡ Read /src/views/session-tree-provider.ts' },
  { type: 'tool' as const, text: '⚡ Read /src/state/reef-state-manager.ts' },
  { type: 'agent' as const, text: "kev ▸ Got it. The tree provider needs to implement `TreeDataProvider<TreeItem>`. I'll create the squad grouping logic first." },
  { type: 'tool' as const, text: '⚡ Write /src/views/session-tree-provider.ts (142 lines)' },
  { type: 'agent' as const, text: 'kev ▸ Created the SessionTreeProvider with:' },
  { type: 'info' as const, text: '    • Squad grouping with collapsible tree items' },
  { type: 'info' as const, text: '    • Status icons (🟢 working, 🟡 idle, 🔴 error)' },
  { type: 'info' as const, text: '    • Cost display per agent and per squad' },
  { type: 'info' as const, text: '    • Auto-refresh on state changes' },
  { type: 'agent' as const, text: 'kev ▸ Now wiring up the context menu actions — right-click to open terminal, stop session, move to squad...' },
  { type: 'tool' as const, text: '⚡ Edit /src/extension.ts' },
  { type: 'tool' as const, text: '⚡ Edit /package.json (adding menus contribution)' },
  { type: 'agent' as const, text: 'kev ▸ ▊' },
];

export const MOCK_TERMINAL_LINES_SENTINEL = [
  { type: 'system' as const, text: 'agent:sentinel:session:b4a2c8 connected' },
  { type: 'agent' as const, text: 'sentinel ▸ Running security audit on the API client implementation...' },
  { type: 'tool' as const, text: '⚡ Read /src/api/openclaw-client.ts' },
  { type: 'agent' as const, text: 'sentinel ▸ ⚠ Warning: API token is stored in settings.json' },
  { type: 'info' as const, text: '    → Should use vscode.SecretStorage instead' },
  { type: 'info' as const, text: '    → Creating fix now...' },
  { type: 'tool' as const, text: '⚡ Edit /src/api/openclaw-client.ts' },
  { type: 'agent' as const, text: 'sentinel ▸ ✅ Migrated token storage to SecretStorage' },
  { type: 'agent' as const, text: 'sentinel ▸ ▊' },
];

export const MOCK_TERMINAL_LINES_SCOUT = [
  { type: 'system' as const, text: 'agent:scout:session:d7e1f9 connected' },
  { type: 'agent' as const, text: 'scout ▸ Researching VS Code webview best practices for the cost dashboard...' },
  { type: 'info' as const, text: '    🌐 Fetched: VS Code Webview API docs' },
  { type: 'info' as const, text: '    🌐 Fetched: Recharts documentation' },
  { type: 'agent' as const, text: 'scout ▸ Key findings:' },
  { type: 'info' as const, text: "    • Use `getWebviewContent()` with nonce for CSP" },
  { type: 'info' as const, text: '    • Recharts supports dark theme via custom colors' },
  { type: 'info' as const, text: '    • postMessage API for extension ↔ webview comms' },
  { type: 'agent' as const, text: 'scout ▸ Compiling findings into research brief... ▊' },
];
